import { Agent, AgentCategory } from "./types";
import { loadPrompt } from "./promptLoader";

export const categories: AgentCategory[] = [
  {
    id: "design",
    name: "Design",
    description: "Agents for UI/UX design, branding, and visual storytelling",
    icon: "Palette",
  },
  {
    id: "engineering",
    name: "Engineering",
    description: "Agents for development, architecture, and technical implementation",
    icon: "Code",
  },
  {
    id: "marketing",
    name: "Marketing",
    description: "Agents for growth, content creation, and social media marketing",
    icon: "TrendingUp",
  },
  {
    id: "product",
    name: "Product",
    description: "Agents for product management, research, and strategy",
    icon: "Target",
  },
  {
    id: "project-management",
    name: "Project Management",
    description: "Agents for project coordination, delivery, and team collaboration",
    icon: "Users",
  },
];

export const agentMetadata = [
  {
    id: "brand-guardian",
    name: "Brand Guardian",
    description: "Strategic brand guardian who ensures every pixel, word, and interaction reinforces brand identity across all touchpoints.",
    category: "design",
    tags: ["branding", "visual-identity", "design-systems", "brand-guidelines"],
    featured: true,
    usageCount: 1856,
    rating: 4.7,
  },
  {
    id: "ui-designer",
    name: "UI Designer",
    description: "Visionary UI designer creating beautiful, implementable interfaces that balance innovation with usability for rapid development.",
    category: "design",
    tags: ["ui-design", "interface", "components", "visual-design"],
    featured: true,
    usageCount: 2134,
    rating: 4.5,
  },
  {
    id: "ux-researcher",
    name: "UX Researcher",
    description: "Empathetic UX researcher bridging user needs and rapid product development through lean research methodologies.",
    category: "design",
    tags: ["user-research", "usability", "journey-mapping", "behavioral-analysis"],
    featured: false,
    usageCount: 892,
    rating: 4.3,
  },
  {
    id: "visual-storyteller",
    name: "Visual Storyteller",
    description: "Masterful visual storyteller transforming complex ideas into captivating visual narratives and compelling data visualizations.",
    category: "design",
    tags: ["visual-storytelling", "infographics", "data-visualization", "presentations"],
    featured: false,
    usageCount: 743,
    rating: 4.6,
  },
  {
    id: "whimsy-injector",
    name: "Whimsy Injector",
    description: "Master of digital delight who transforms functional interfaces into joyful experiences users can't help but share.",
    category: "design",
    tags: ["delight", "micro-interactions", "animations", "user-joy"],
    featured: true,
    usageCount: 1567,
    rating: 4.4,
  },
  {
    id: "ai-engineer",
    name: "AI Engineer",
    description: "Expert AI engineer specializing in practical machine learning implementation and AI integration for production applications.",
    category: "engineering",
    tags: ["ai", "machine-learning", "llm", "computer-vision"],
    featured: true,
    usageCount: 1923,
    rating: 4.7,
  },
  {
    id: "backend-architect",
    name: "Backend Architect",
    description: "Master backend architect designing scalable, secure, and maintainable server-side systems for rapid development cycles.",
    category: "engineering",
    tags: ["backend", "architecture", "apis", "databases"],
    featured: true,
    usageCount: 2087,
    rating: 4.6,
  },
  {
    id: "devops-automator",
    name: "DevOps Automator",
    description: "DevOps automation expert transforming manual deployment nightmares into smooth, automated workflows.",
    category: "engineering",
    tags: ["devops", "ci-cd", "infrastructure", "automation"],
    featured: false,
    usageCount: 934,
    rating: 4.5,
  },
  {
    id: "frontend-developer",
    name: "Frontend Developer",
    description: "Elite frontend specialist building responsive, accessible, and performant web applications with modern JavaScript frameworks.",
    category: "engineering",
    tags: ["frontend", "react", "javascript", "performance"],
    featured: true,
    usageCount: 2456,
    rating: 4.8,
  },
  {
    id: "mobile-app-builder",
    name: "Mobile App Builder",
    description: "Expert mobile developer creating smooth, native-feeling mobile experiences across iOS, Android, and cross-platform.",
    category: "engineering",
    tags: ["mobile", "ios", "android", "react-native"],
    featured: false,
    usageCount: 1234,
    rating: 4.6,
  },
  {
    id: "rapid-prototyper",
    name: "Rapid Prototyper",
    description: "Elite rapid prototyping specialist transforming ideas into functional applications at breakneck speed for quick validation.",
    category: "engineering",
    tags: ["prototyping", "mvp", "rapid-development", "validation"],
    featured: true,
    usageCount: 1687,
    rating: 4.7,
  },
  {
    id: "test-writer-fixer",
    name: "Test Writer & Fixer",
    description: "Elite test automation expert specializing in comprehensive test writing and maintaining test suite integrity.",
    category: "engineering",
    tags: ["testing", "automation", "tdd", "quality"],
    featured: false,
    usageCount: 867,
    rating: 4.4,
  },
  {
    id: "app-store-optimizer",
    name: "App Store Optimizer",
    description: "ASO maestro maximizing organic app visibility and downloads through keyword research and conversion optimization.",
    category: "marketing",
    tags: ["aso", "app-store", "keywords", "conversion"],
    featured: false,
    usageCount: 745,
    rating: 4.3,
  },
  {
    id: "content-creator",
    name: "Content Creator",
    description: "Cross-platform content specialist creating engaging content from blog posts to video scripts while maintaining brand consistency.",
    category: "marketing",
    tags: ["content", "writing", "video-scripts", "seo"],
    featured: true,
    usageCount: 1432,
    rating: 4.5,
  },
  {
    id: "growth-hacker",
    name: "Growth Hacker",
    description: "Data-driven growth specialist creating viral loops and scaling user acquisition through rapid experimentation.",
    category: "marketing",
    tags: ["growth", "viral", "experiments", "acquisition"],
    featured: true,
    usageCount: 1678,
    rating: 4.6,
  },
  {
    id: "instagram-curator",
    name: "Instagram Curator",
    description: "Instagram specialist creating visually stunning content and building engaged communities through strategic curation.",
    category: "marketing",
    tags: ["instagram", "social-media", "visual-content", "community"],
    featured: false,
    usageCount: 634,
    rating: 4.2,
  },
  {
    id: "reddit-community-builder",
    name: "Reddit Community Builder",
    description: "Reddit specialist building authentic communities and driving organic engagement through valuable contributions.",
    category: "marketing",
    tags: ["reddit", "community", "organic-marketing", "engagement"],
    featured: false,
    usageCount: 523,
    rating: 4.3,
  },
  {
    id: "tiktok-strategist",
    name: "TikTok Strategist",
    description: "TikTok expert creating viral content and building massive audiences through trend analysis and strategic content planning.",
    category: "marketing",
    tags: ["tiktok", "viral", "trends", "short-form-video"],
    featured: true,
    usageCount: 1834,
    rating: 4.7,
  },
  {
    id: "twitter-engager",
    name: "Twitter Engager",
    description: "Twitter specialist building thought leadership and driving meaningful engagement through strategic content and community building.",
    category: "marketing",
    tags: ["twitter", "engagement", "thought-leadership", "community"],
    featured: false,
    usageCount: 789,
    rating: 4.4,
  },
  {
    id: "feedback-synthesizer",
    name: "Feedback Synthesizer",
    description: "Product feedback specialist transforming user insights into actionable product decisions through systematic analysis.",
    category: "product",
    tags: ["feedback", "user-insights", "product-decisions", "analysis"],
    featured: false,
    usageCount: 456,
    rating: 4.2,
  },
  {
    id: "sprint-prioritizer",
    name: "Sprint Prioritizer",
    description: "Agile product specialist optimizing sprint planning and feature prioritization for maximum impact and team velocity.",
    category: "product",
    tags: ["agile", "sprint-planning", "prioritization", "velocity"],
    featured: false,
    usageCount: 623,
    rating: 4.3,
  },
  {
    id: "trend-researcher",
    name: "Trend Researcher",
    description: "Trend analysis specialist identifying emerging opportunities and market shifts to guide product strategy and innovation.",
    category: "product",
    tags: ["trends", "market-research", "innovation", "strategy"],
    featured: false,
    usageCount: 387,
    rating: 4.4,
  },
  {
    id: "experiment-tracker",
    name: "Experiment Tracker",
    description: "Project experiment specialist managing and tracking rapid experiments to validate ideas and optimize outcomes.",
    category: "project-management",
    tags: ["experiments", "tracking", "validation", "optimization"],
    featured: false,
    usageCount: 298,
    rating: 4.2,
  },
  {
    id: "project-shipper",
    name: "Project Shipper",
    description: "Project delivery specialist ensuring projects ship on time with quality through effective coordination and risk management.",
    category: "project-management",
    tags: ["project-delivery", "shipping", "coordination", "risk-management"],
    featured: false,
    usageCount: 512,
    rating: 4.5,
  },
  {
    id: "studio-producer",
    name: "Studio Producer",
    description: "Creative studio specialist orchestrating complex creative projects and ensuring seamless collaboration across teams.",
    category: "project-management",
    tags: ["production", "creative-projects", "team-coordination", "workflow"],
    featured: false,
    usageCount: 445,
    rating: 4.3,
  },
];

export async function createAgentWithPrompt(agentMeta: typeof agentMetadata[number]): Promise<Agent> {
  const prompt = await loadPrompt(agentMeta.id);
  return {
    ...agentMeta,
    prompt,
  };
}

export async function getAgentsWithPrompts(): Promise<Agent[]> {
  const agents = await Promise.all(
    agentMetadata.map(async (agentMeta) => {
      return await createAgentWithPrompt(agentMeta);
    })
  );
  return agents;
}

export const agents: Agent[] = agentMetadata.map(meta => ({
  ...meta,
  prompt: ''
}));
